-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 19:48:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema balivista
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema balivista
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `balivista` DEFAULT CHARACTER SET utf8 ;
USE `balivista` ;

-- -----------------------------------------------------
-- Table `balivista`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balivista`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balivista`.`favorite_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balivista`.`favorite_movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `movietouser_idx` (`user_id` ASC),
  CONSTRAINT `movietouser`
    FOREIGN KEY (`user_id`)
    REFERENCES `balivista`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
